version: '3.7'

services:
  nistagram-campaigns-db:
    container_name: nistagram-campaigns-db
    image: mysql:8.0.19
    restart: always
    ports:
      - 3306
    command: '--default-authentication-plugin=mysql_native_password'
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--silent"]
      interval: 3s
      retries: 5
      start_period: 30s
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=nistagramcampaignsschema

  nistagram-campaigns:
    container_name: nistagram-campaigns
    build:
      context: .
    depends_on:
      nistagram-campaigns-db:
          condition: service_healthy
    environment:
      - mysql_username=root
      - mysql_password=root
      - mysql_host=nistagram-campaigns-db:3306
      - mysql_schema=nistagramcampaignsschema